### ISSUE TITLE
forgot

### ISSUE THREAD

**Issue by sec13b** [prajxwal/WindowsDefenderBypass-csharp#1]
you forgot to add " or compile using the command line"  :P

**Comment by prajxwal** [comment]
will add :))

ps : if u want to collab on some projects hmu

**Comment by sec13b** [comment]
cl.exe  bypass.cs /out:bypasscs.exe
Microsoft (R) C/C++ Optimizing Compiler Version 19.38.33135 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

cl : Command line warning D9035 : option 'o' has been deprecated and will be removed in a future release
cl : Command line warning D9024 : unrecognized source file type 'bypass.cs', object file assumed
Microsoft (R) Incremental Linker Version 14.38.33135.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:bypass.exe
/out:ut:bypasscs.exe
bypass.cs
bypass.cs : fatal error LNK1107: invalid or corrupt file: cannot read at 0xE41

**Comment by prajxwal** [comment]
i think you're using c++ compiler instead c# compiler

**Comment by sec13b** [comment]
please add in the "Releases" the exe
thank you
